### ISSUE TITLE
AP mode not working

### ISSUE THREAD

**Issue by mintu19** [al177/esp8089#37] opened 2019-08-31 05:20 UTC
I try
```
pi@raspberry:~$ sudo hostapd /etc/hostapd/hostapd.conf
Configuration file: /etc/hostapd/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED
hostapd_free_hapd_data: Interface wlan0 wasn't started
```

Note that i tried this while connected to wifi and while disconnected as well (but wifi was up).

If i remove wpa suppliment hook from dhchcd conf file then access point works but not directly. I need to switch between AP mode and client mode.

**Comment by al177** [comment] 2023-03-06 20:57
Probably way too late, but a recent commit may have fixed your issue. Closing for now with the assumption that it's a dupe of #52. If that's not the case, feel free to reopen.

**Closed as completed by al177** 2023-03-06 20:57 UTC
